---
ansible_connection: local

app_name: "omp-data-api"
ci_cd_namespace: "omp-ci-cd"
dev_namespace: "omp-dev"

ci_cd:
  NAMESPACE: "{{ ci_cd_namespace }}"
  NAMESPACE_DISPLAY_NAME: "{{ app_name }} CI/CD"

dev:
  NAMESPACE: "{{ dev_namespace }}"
  NAMESPACE_DISPLAY_NAME: "{{ app_name }} Dev"
  
build:
  NAME: "{{ app_name }}"
  PIPELINE_SOURCE_REPOSITORY_URL: https://github.com/rht-labs/omp-data-api
  PIPELINE_SOURCE_REPOSITORY_REF: master
  S2I_BASE_IMAGE: nodejs:10

mgob_build:
  NAME: "{{ app_name }}-mgob"
  SOURCE_REPOSITORY_URL: https://github.com/tylerauerbeck/mgob
  SOURCE_REPOSITORY_REF: master

deploy:
  NAME: "{{ app_name }}"
  PIPELINES_NAMESPACE: "{{ ci_cd_namespace }}"
  DATABASE_CONNECTION_STRING: "mongodb://{{ db_deploy.MONGODB_USER }}:{{ db_deploy.MONGODB_PASSWORD }}@{{ db_deploy.DATABASE_SERVICE_NAME}}:27017/{{ db_deploy.MONGODB_DATABASE }}"

db_deploy:
  MONGODB_USER: "omp-user"
  MONGODB_DATABASE: "{{ app_name }}-db"
  MONGODB_VERSION: "3.4"
  VOLUME_CAPACITY: "5Gi"
  MEMORY_LIMIT: "512Mi"
  DATABASE_SERVICE_NAME: "{{ app_name }}-mongo"
  MONGODB_PASSWORD: "user-password"
  MONGODB_ADMIN_PASSWORD: "admin-password"

mgob_deploy:
  NAME: "{{ app_name }}"
  NAMESPACE: "{{ dev_namespace }}"
  MONGODB_SVC: "{{ db_deploy.DATABASE_SERVICE_NAME }}"
  MONGODB_PORT: 27017
  MONGODB_USERNAME: "admin"
  MONGODB_PASSWORD: "{{ db_deploy.MONGODB_ADMIN_PASSWORD }}"
  MONGODB_DATABASE: "{{ db_deploy.MONGODB_DATABASE }}"
  SCHEDULE: "0 0 1 * *"
  BACKUP_RETENTION: 5
  BACKUP_TIMEOUT: 60
  BACKUP_BUCKET_URL: "https://s3.amazonaws.com/"
  BACKUP_BUCKET_NAME: "my-test-bucket"
  BACKUP_ACCESSKEY: "my-test-access-key"
  BACKUP_SECRETKEY: "my-test-secret-key"
  S3_PROTOCOL: "S3v4"

openshift_cluster_content:
  - object: projectrequest
    content:
      - name: "{{ ci_cd_namespace }}-project"
        template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.10.0/files/projectrequest/template.yml"
        action: create
        params_from_vars: "{{ ci_cd }}"
        tags:
          - projectrequest
      - name: "{{ dev_namespace }}-project"
        template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.10.0/files/projectrequest/template.yml"
        action: create
        params_from_vars: "{{ dev }}"
        tags:
          - projectrequest
  - object: app-build
    content:
      - name: "{{ app_name }}-build"
        template: "https://raw.githubusercontent.com/rht-labs/labs-ci-cd/v3.10.0/openshift-templates/s2i-app-build/template-no-secrets.yml"
        params_from_vars: "{{ build }}"
        namespace: "{{ ci_cd_namespace }}"
        tags:
          - app-build
      - name: "{{ app_name }}-mgob-build"
        template: "{{ inventory_dir }}/../templates/omp-db/build.yaml" 
        params_from_vars: "{{ mgob_build }}"
        namespace: "{{ dev_namespace }}"
        tags:
          - mgob-build

  - object: db-deploy
    content:
      - name: "{{ app_name }}-db-deploy-{{ dev_namespace }}"
        template: "openshift//mongodb-persistent"
        params_from_vars: "{{ db_deploy }}"
        namespace: "{{ dev_namespace }}"
        tags:
          - db-deploy
          - mongo-deploy

  - object: app-deploy
    content:
      - name: "{{ app_name }}-deploy-{{ dev_namespace }}"
        template: "{{ inventory_dir }}/../templates/omp-data-api/deploy.yml"
        params_from_vars: "{{ deploy }}"
        namespace: "{{ dev_namespace }}"
        tags:
          - app-deploy
      - name: "{{ app_name }}"
        template: "{{ inventory_dir }}/../templates/omp-db/mgob-template.yaml" 
        params_from_vars: "{{ mgob_deploy }}"
        namespace: "{{ dev_namespace }}"
        tags:
          - mgob-deploy
          - mongo-deploy
