# This is the Ansible Galaxy requirements file to pull in the correct roles
# to support the operation of CASL provisioning/runs.
# version 2 of the applier is newer than version 3

# From 'openshift-applier'
- src: https://github.com/redhat-cop/openshift-applier
  scm: git
  version: v2.0.9
  name: openshift-applier
